In [25]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
data_file = pd.read_csv("movies.csv")
data_file.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [12]:
data_file.shape

(4803, 24)

In [20]:
sel_features = ['genres', 'keywords', 'overview', 'cast', 'director']
print(sel_features)

['genres', 'keywords', 'overview', 'cast', 'director']


In [21]:
for feature in sel_features:
    data_file[feature] = data_file[feature].fillna(' ')

In [24]:
main_data = data_file['genres'] + data_file ['keywords'] + data_file ['overview'] + data_file['cast'] +  data_file['director'] 
main_data.head()

0    Action Adventure Fantasy Science Fictioncultur...
1    Adventure Fantasy Actionocean drug abuse exoti...
2    Action Adventure Crimespy based on novel secre...
3    Action Crime Drama Thrillerdc comics crime fig...
4    Action Adventure Science Fictionbased on novel...
dtype: object

In [26]:
vectorizer = TfidfVectorizer()

In [27]:
feature_vectors = vectorizer.fit_transform(main_data)

In [28]:
print(feature_vectors)

  (0, 5304)	0.1359612384400969
  (0, 30026)	0.2232291004912191
  (0, 23431)	0.12458698160995665
  (0, 20682)	0.1776951456805665
  (0, 33653)	0.12764578194701906
  (0, 38462)	0.15708698903122817
  (0, 32344)	0.16116177423991973
  (0, 30880)	0.1756610216272418
  (0, 39715)	0.15276934751925222
  (0, 39255)	0.19139265515600729
  (0, 30926)	0.11834630019710517
  (0, 6500)	0.17377771691301558
  (0, 1316)	0.128243762102363
  (0, 1578)	0.05672845478317086
  (0, 28115)	0.17377771691301558
  (0, 1613)	0.03285112128175772
  (0, 25883)	0.1660170579241967
  (0, 14028)	0.14774200505958093
  (0, 3685)	0.10471719718032763
  (0, 35963)	0.15122869497207092
  (0, 3352)	0.1001238513339855
  (0, 5111)	0.06427622483792225
  (0, 23720)	0.1140222550101429
  (0, 37213)	0.15804608338425008
  (0, 25763)	0.051648609499337944
  :	:
  (4802, 36434)	0.07868928692424045
  (4802, 35180)	0.06856984025552768
  (4802, 25428)	0.06379758497129925
  (4802, 16016)	0.08151556198973951
  (4802, 38546)	0.07720722681602471
  (48

In [29]:
similarity = cosine_similarity(feature_vectors)

In [30]:
print(similarity)
print(similarity.shape)

[[1.         0.03009604 0.02072976 ... 0.01794939 0.03213846 0.00579764]
 [0.03009604 1.         0.02711757 ... 0.03420998 0.02013721 0.01354583]
 [0.02072976 0.02711757 1.         ... 0.02741251 0.02427449 0.01160535]
 ...
 [0.01794939 0.03420998 0.02741251 ... 1.         0.03955662 0.02693193]
 [0.03213846 0.02013721 0.02427449 ... 0.03955662 1.         0.03131158]
 [0.00579764 0.01354583 0.01160535 ... 0.02693193 0.03131158 1.        ]]
(4803, 4803)


In [32]:
movie_input = input("Enter Your Favourite Movie Name: ")

Enter Your Favourite Movie Name:  Nebraska


In [36]:
list_movies = data_file['original_title'].tolist()
print(list_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [39]:
import difflib
find_match = difflib.get_close_matches(movie_input, list_movies)
print(find_match)

['Nebraska']


In [40]:
close_match = find_match[0]
print(close_match)

Nebraska


In [43]:
index_input = data_file[data_file.title == close_match]['index'].values[0]
print(index_input)

2849


In [46]:
similarity_score = list(enumerate(similarity[index_input]))
print(similarity_score)

[(0, 0.0030355488388995), (1, 0.02401449309791239), (2, 0.0115556889639988), (3, 0.006208650968695023), (4, 0.010708845882721444), (5, 0.004872784472966209), (6, 0.007470399674329325), (7, 0.014801606133861922), (8, 0.00849098162260917), (9, 0.02165560097357925), (10, 0.011245446821074836), (11, 0.01030413386099284), (12, 0.010950534705430089), (13, 0.007747109960057326), (14, 0.03997548841682924), (15, 0.010825778490474315), (16, 0.007241043804107117), (17, 0.021246385388434035), (18, 0.03881480432206645), (19, 0.02050767212687068), (20, 0.059776511632241736), (21, 0.024356334456228958), (22, 0.0061220387123459554), (23, 0.0013670325676330595), (24, 0.012358931507750161), (25, 0.011147393539337549), (26, 0.00713399177211744), (27, 0.018988883001947166), (28, 0.0), (29, 0.02719848669264608), (30, 0.016496955187015234), (31, 0.0034181719500099507), (32, 0.016152991698750667), (33, 0.0029320771383599966), (34, 0.0), (35, 0.00760168993334411), (36, 0.016825852328291382), (37, 0.0264018387

In [48]:
sorting_similarity = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorting_similarity)

[(2849, 1.0000000000000002), (3094, 0.12741640867395412), (2210, 0.09713146491046354), (3684, 0.08906987428268327), (2268, 0.0884786944375107), (3972, 0.08831531323477039), (3401, 0.08768068941177651), (3051, 0.08165997051982898), (3055, 0.08077742002415411), (3481, 0.07900564225193171), (3116, 0.07864452908535387), (4242, 0.0759115373700399), (3765, 0.07535120134951695), (4662, 0.07529992486683404), (2102, 0.07279116532629488), (1218, 0.07271167593540778), (3491, 0.07259282712862827), (4417, 0.07242379361419679), (4174, 0.07165597840490198), (1566, 0.071500166336375), (2862, 0.07144212872216428), (4423, 0.07109380785705229), (954, 0.06947461762556037), (3318, 0.0693123311442458), (1082, 0.06927547156647487), (3171, 0.06844020892603293), (4450, 0.06842211574575205), (4789, 0.06823564163879532), (3633, 0.068235495082222), (3944, 0.06808695648154639), (3148, 0.06774465299570316), (4079, 0.0664793642379616), (2927, 0.06605450497301078), (193, 0.06556549729659425), (2713, 0.064643698795209

In [62]:
print('Movies Suggested: \n')

i = 1
for movie in sorting_similarity:
    index = movie[0]
    title_index = data_file[data_file.index==index]['original_title'].values[0]
    if (i < 10):
        print(i, ".", title_index)
        i=i+1

Movies Suggested: 

1 . Nebraska
2 . The Brothers Solomon
3 . Be Kind Rewind
4 . Pat Garrett & Billy the Kid
5 . 三国之见龙卸甲
6 . Chicago Overcoat
7 . Twixt
8 . MacGruber
9 . Seeking a Friend for the End of the World
